Q1. What are data structures, and why are they important?
      
  Ans-Data structures are techniques to organize, store, and manage data      
      efficiently. They are important for optimizing algorithms, improving performance, and enabling scalable solutions for complex problems.

Q2. Explain the difference between mutable and immutable data types with examples.

  Ans-Mutable Data Types: Can be modified after creation. Examples: list,
   dictionary, set.

     my_list = [1, 2, 3]
     my_list[0] = 10  # List is mutable

  Immutable Data Types: Cannot be changed after creation. Examples: tuple, string.

  my_tuple = (1, 2, 3)
  # my_tuple[0] = 10  # Throws an error, as tuples are immutable

Q3. What are the main differences between lists and tuples in Python?

  Ans-Lists are mutable; tuples are immutable.

  Tuples are faster and consume less memory than lists.

  Lists are used for dynamic data, while tuples are used for static data.

Q4. Describe how dictionaries store data.
      
      Ans-Dictionaries store data as key-value pairs using hash tables.
      Each key is hashed to generate an index for efficient storage and retrieval.

Q5. Why might you use a set instead of a list in Python?
  
   Ans-A set is used when:Unique elements are required (duplicates are removed).
      Fast membership checks are needed (in operator).

Q6. What is a string in Python, and how is it different from a list?

  Ans-A string is a sequence of characters. It is immutable, unlike a list, which is mutable and can hold elements of various data types.

Q7. How do tuples ensure data integrity in Python?

   Ans-Tuples are immutable, meaning their data cannot be altered after creation, ensuring data consistency and preventing accidental modifications.

Q8. What is a hash table, and how does it relate to dictionaries in Python?

  Ans-A hash table is a data structure that maps keys to values using a hash function. Python dictionaries are implemented using hash tables, providing O(1) average time complexity for key-based lookups.

Q9. Can lists contain different data types in Python?

  Ans-Yes, Python lists can contain elements of different data types.
Example:

my_list = [1, "hello", 3.14, [1, 2]]

Q10. Explain why strings are immutable in Python.

  Ans-Strings are immutable for reasons such as:

  (1)Memory optimization (string interning).

  (2)Thread safety and security.

  (3)Easier debugging and predictable behavior.

Q11. What advantages do dictionaries offer over lists for certain tasks?

  Ans-Dictionaries provide:

Faster lookups (O(1) average time complexity).

The ability to store data as key-value pairs, making them suitable for structured data storage.

Q12. Describe a scenario where using a tuple would be preferable over a list.

  Ans-Tuples are preferable when storing data that should not change, such as configuration settings or coordinates (x, y).

Q13. How do sets handle duplicate values in Python?

  Ans-Sets automatically eliminate duplicate values.
Example:

my_set = {1, 2, 2, 3}

print(my_set)  # Output: {1, 2, 3}

Q14. How does the in keyword work differently for lists and dictionaries?

  Ans-Lists: Checks if the value exists in the list.

Dictionaries: Checks if the key exists in the dictionary

Q15. Can you modify the elements of a tuple? Explain why or why not.

  Ans-No, tuples are immutable, so their elements cannot be modified after creation.

Q16. What is a nested dictionary, and give an example of its use case.

Ans-A nested dictionary is a dictionary within another dictionary.
  Example:

  students = {"Alice": {"Math": 85, "Science": 90},
    "Bob": {"Math": 78, "Science": 88}}

  Use case: Storing hierarchical data like student grades.

Q17. Describe the time complexity of accessing elements in a dictionary.

  Ans-The average time complexity for accessing elements in a dictionary is O(1), due to its hash table implementation.

Q18. In what situations are lists preferred over dictionaries?

  Ans-Lists are preferred when:

  *Order of elements is important.

  *The dataset does not require key-value pairs.

  *Sequential data processing is needed.

Q19. Why are dictionaries considered unordered, and how does that affect data retrieval?

  Ans-Dictionaries are unordered because they store data based on hash values. Until Python 3.7, they did not preserve insertion order. Retrieval depends on keys, not the position of elements.

Q20. Explain the difference between a list and a dictionary in terms of data retrieval.

  Ans-List: Access elements by their index.

  Dictionary: Access elements by their key, which is faster and more descriptive.

In [2]:
#Practical Q/A

In [3]:
#Q1. Write a code to create a string with your name and print it.

name = "Revil"
print(name)

Revil

In [4]:
#Q2. Write a code to find the length of the string "Hello World".

string = "Hello World"
print(len(string))

11

In [7]:
#Q3. Write a code to slice the first 3 characters from the string "Python Programming".
string = "Python Programming"
sliced_string = string[:3]
print(sliced_string)  # Output: Pyt

Pyt

In [8]:
#Q4. Write a code to convert the string "hello" to uppercase.

string = "hello"
print(string.upper())  # Output: "HELLO"

HELLO

In [9]:
#Q5. Write a code to replace the word "apple" with "orange" in the string "I like apple".

string = "I like apple"
new_string = string.replace("apple", "orange")
print(new_string)  # Output: "I like orange"

I like orange

In [10]:
#Q6. Write a code to create a list with numbers 1 to 5 and print it.

my_list = [1, 2, 3, 4, 5]
print(my_list)

[1, 2, 3, 4, 5]

In [11]:
#Q7. Write a code to append the number 10 to the list [1, 2, 3, 4].

my_list = [1, 2, 3, 4]
my_list.append(10)
print(my_list)  # Output: [1, 2, 3, 4, 10]

[1, 2, 3, 4, 10]

In [12]:
#Q8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].

my_list = [1, 2, 3, 4, 5]
my_list.remove(3)
print(my_list)  # Output: [1, 2, 4, 5]

[1, 2, 4, 5]

In [13]:
#Q9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].

my_list = ['a', 'b', 'c', 'd']
print(my_list[1])  # Output: 'b'

b

In [14]:
#Q10. Write a code to reverse the list [10, 20, 30, 40, 50].

my_list = [10, 20, 30, 40, 50]
my_list.reverse()
print(my_list)  # Output: [50, 40, 30, 20, 10]

[50, 40, 30, 20, 10]

In [15]:
#Q11. Write a code to create a tuple with the elements 10, 20, 30 and print it.

my_tuple = (10, 20, 30)
print(my_tuple)

(10, 20, 30)

In [19]:
#Q12. Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').

my_tuple = ('apple', 'banana', 'cherry')
print(my_tuple[0])  # Output: 'apple'

apple

In [18]:
#Q13. Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2).

my_tuple = (1, 2, 3, 2, 4, 2)
print(my_tuple.count(2))  # Output: 3

3

In [21]:
#Q14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

my_tuple = ('dog', 'cat', 'rabbit')
print(my_tuple.index("cat"))  # Output: 1

1

In [23]:
#Q15. Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').

my_tuple = ('apple', 'orange', 'banana')
print("banana" in my_tuple)  # Output: True

True

In [24]:
#Q16. Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.

my_set = {1, 2, 3, 4, 5}
print(my_set)

{1, 2, 3, 4, 5}

In [25]:
#Q17. Write a code to add the element 6 to the set {1, 2, 3, 4}.

my_set = {1, 2, 3, 4}
my_set.add(6)
print(my_set)  # Output: {1, 2, 3, 4, 6}

{1, 2, 3, 4, 6}

In [34]:
#Q18. Write a code to create a tuple with the elements 10, 20, 30 and print it.

my_tuple = (10, 20, 30)
print(my_tuple)

(10, 20, 30)

In [36]:
#Q19. Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').

my_tuple = ('apple', 'banana', 'cherry')
print(my_tuple[0])  # Output: 'apple'

apple

In [37]:
#Q20. Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2).

my_tuple = (1, 2, 3, 2, 4, 2)
print(my_tuple.count(2))  # Output: 3

3

In [39]:
#Q21. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

my_tuple = ('dog', 'cat', 'rabbit')
print(my_tuple.index("cat"))  # Output: 1

1

In [40]:
#Q22. Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').

my_tuple = ('apple', 'orange', 'banana')
print("banana" in my_tuple)  # Output: True

True

In [41]:
#Q23. Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.

my_set = {1, 2, 3, 4, 5}
print(my_set)

{1, 2, 3, 4, 5}

In [42]:
#Q24. Write a code to add the element 6 to the set {1, 2, 3, 4}.

my_set = {1, 2, 3, 4}
my_set.add(6)
print(my_set)  # Output: {1, 2, 3, 4, 6}

{1, 2, 3, 4, 6}